# Generated by Django 3.2.6 on 2021-08-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='on_menu',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
