# Generated by Django 3.2.6 on 2021-08-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_page_on_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='on_menu',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
