# Generated by Django 3.2.6 on 2021-09-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_album_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
