# Generated by Django 3.2.5 on 2021-08-15 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_auto_20210815_1036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamplayer',
            old_name='user',
            new_name='player',
        ),
    ]
