# Generated by Django 3.2.6 on 2021-08-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_auto_20210826_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
