# Generated by Django 3.2.6 on 2021-08-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0008_alter_club_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='contacts'),
        ),
    ]
