# Generated by Django 3.2.6 on 2021-08-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0014_auto_20210830_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='title',
            field=models.JSONField(blank=True, max_length=255, null=True),
        ),
    ]
