# Generated by Django 3.2.6 on 2021-08-20 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
    ]