# Generated by Django 3.2.5 on 2021-08-02 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='game',
            table='games',
        ),
        migrations.AlterModelTable(
            name='group',
            table='groups',
        ),
        migrations.AlterModelTable(
            name='level',
            table='levels',
        ),
        migrations.AlterModelTable(
            name='type',
            table='types',
        ),
    ]
