# Generated by Django 3.2.5 on 2021-08-02 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competitions', '0002_auto_20210802_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_away', to=settings.AUTH_USER_MODEL, verbose_name='Player Away'),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_a2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_away_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_h',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_home', to=settings.AUTH_USER_MODEL, verbose_name='Player Home'),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_h2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_home_2', to=settings.AUTH_USER_MODEL),
        ),
    ]
