# Generated by Django 3.2.5 on 2021-07-22 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_contact_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ClubResponsable',
            old_name='contact',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='ClubResponsable',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='competitions.club'),
        ),
    ]
