# Generated by Django 3.2.6 on 2021-08-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_auto_20210823_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
