# Generated by Django 3.2.5 on 2021-07-22 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_auto_20210722_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='competitions.contact'),
        ),
    ]
