# Generated by Django 3.2.6 on 2021-08-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_alter_level_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={},
        ),
        migrations.RemoveField(
            model_name='group',
            name='reference',
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
