# Generated by Django 3.2.5 on 2021-07-25 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_auto_20210722_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubresponsable',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsables', to='competitions.club'),
        ),
    ]
