# Generated by Django 3.2.5 on 2021-07-25 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_alter_clubresponsable_club'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubresponsable',
            old_name='title',
            new_name='function',
        ),
    ]
