# Generated by Django 3.2.6 on 2021-08-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_auto_20210826_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
