# Generated by Django 3.2.6 on 2021-09-15 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0015_alter_committee_title'),
        ('competitions', '0007_group_link'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Competition',
            new_name='Interclub',
        ),
        migrations.RemoveField(
            model_name='game',
            name='competition',
        ),
    ]
