# Generated by Django 3.2.6 on 2021-09-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0008_auto_20210915_0718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
