# Generated by Django 3.2.5 on 2021-07-26 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0009_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='competitions.level'),
        ),
        migrations.AddField(
            model_name='group',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='competitions.level'),
        ),
    ]
